/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tesina;

import Tesina.User_Pass;
import Tesina.Clases.Account;
import Tesina.Clases.Account_Coms;
import Tesina.Clases.Account_Dom;
import Tesina.Clases.Account_Health;
import Tesina.Clases.Account_Studies;
import Tesina.Clases.Family_Data;
import Tesina.Clases.Family_Dom;
//
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import net.glxn.qrgen.QRCode;
import net.glxn.qrgen.image.ImageType;

/**
 *
 * @author Alan_
 */
public class User_QR extends javax.swing.JFrame {

    DefaultListModel ListModel1 = new DefaultListModel();
    DefaultListModel ListModel2 = new DefaultListModel();
    DefaultListModel ListModel3 = new DefaultListModel();
    DefaultListModel ListModel4 = new DefaultListModel();
    DefaultListModel ListModel5 = new DefaultListModel();
    DefaultListModel ListModel6 = new DefaultListModel();
    DefaultListModel ListModel7 = new DefaultListModel();

    /**
     * Creates new form Qr_User
     */
    public User_QR() {
        initComponents();
        this.jList_Persona.setModel(ListModel1);
        this.jList_Coms.setModel(ListModel2);
        this.jList_Dom.setModel(ListModel3);
        this.jList_Health.setModel(ListModel4);
        this.jList_FamDom.setModel(ListModel5);
        this.jList_Edu.setModel(ListModel6);
        this.jList_Fam.setModel(ListModel7);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Background = new javax.swing.JPanel();
        jPanel_Header = new javax.swing.JPanel();
        jLabel_User = new javax.swing.JLabel();
        jButton_Back = new javax.swing.JButton();
        jButton_Config = new javax.swing.JButton();
        jButton_Search = new javax.swing.JButton();
        jButton_Refresh = new javax.swing.JButton();
        jLabel_Id = new javax.swing.JLabel();
        jLabel_IdSS = new javax.swing.JLabel();
        jLabel_IdEdu = new javax.swing.JLabel();
        jPanel_Doc = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList_Persona = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList_Coms = new javax.swing.JList<>();
        jScrollPane8 = new javax.swing.JScrollPane();
        jList_Health = new javax.swing.JList<>();
        jScrollPane9 = new javax.swing.JScrollPane();
        jList_Edu = new javax.swing.JList<>();
        jScrollPane12 = new javax.swing.JScrollPane();
        jList_Fam = new javax.swing.JList<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        jList_Dom = new javax.swing.JList<>();
        jScrollPane11 = new javax.swing.JScrollPane();
        jList_FamDom = new javax.swing.JList<>();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_Edu = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea_Cert = new javax.swing.JTextArea();
        jButton_GenEdu = new javax.swing.JButton();
        jButton_Certi = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea_Data = new javax.swing.JTextArea();
        jButton_Datos = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea_Dom = new javax.swing.JTextArea();
        jButton_Dom = new javax.swing.JButton();
        jScrollPane17 = new javax.swing.JScrollPane();
        Coms = new javax.swing.JTextArea();
        jButton_Com = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane16 = new javax.swing.JScrollPane();
        jTextArea_DomPad = new javax.swing.JTextArea();
        jButton_PDom = new javax.swing.JButton();
        jScrollPane15 = new javax.swing.JScrollPane();
        jTextArea_Padres = new javax.swing.JTextArea();
        jButton_Padres = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane13 = new javax.swing.JScrollPane();
        jTextArea_Vac = new javax.swing.JTextArea();
        jScrollPane14 = new javax.swing.JScrollPane();
        jTextArea_Ale = new javax.swing.JTextArea();
        jButton_HpGeneral = new javax.swing.JButton();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTextArea_GenHp = new javax.swing.JTextArea();
        jButton_Vacunas = new javax.swing.JButton();
        jButton_Ale = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QR Maker");
        setLocationByPlatform(true);
        setResizable(false);

        jPanel_Background.setBackground(new java.awt.Color(51, 51, 51));

        jPanel_Header.setBackground(new java.awt.Color(102, 102, 102));

        jLabel_User.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel_User.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_User.setText("User");
        jLabel_User.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuario"));

        jButton_Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Logout.png"))); // NOI18N
        jButton_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BackActionPerformed(evt);
            }
        });

        jButton_Config.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Gear-icon.png"))); // NOI18N
        jButton_Config.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ConfigActionPerformed(evt);
            }
        });

        jButton_Search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/search-icon.png"))); // NOI18N
        jButton_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SearchActionPerformed(evt);
            }
        });

        jButton_Refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Refresh-icon.png"))); // NOI18N
        jButton_Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RefreshActionPerformed(evt);
            }
        });

        jLabel_Id.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel_Id.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Id.setBorder(javax.swing.BorderFactory.createTitledBorder("ID"));

        jLabel_IdSS.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel_IdSS.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_IdSS.setBorder(javax.swing.BorderFactory.createTitledBorder("ID SS"));

        jLabel_IdEdu.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel_IdEdu.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_IdEdu.setBorder(javax.swing.BorderFactory.createTitledBorder("ID EDU"));

        javax.swing.GroupLayout jPanel_HeaderLayout = new javax.swing.GroupLayout(jPanel_Header);
        jPanel_Header.setLayout(jPanel_HeaderLayout);
        jPanel_HeaderLayout.setHorizontalGroup(
            jPanel_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_User, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_IdSS, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_IdEdu, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_Search)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Refresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Config)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Back)
                .addContainerGap())
        );
        jPanel_HeaderLayout.setVerticalGroup(
            jPanel_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Config, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Back, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Search, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Refresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_User, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_IdSS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_IdEdu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel_Doc.setBackground(new java.awt.Color(51, 51, 51));
        jPanel_Doc.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Docs", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel_Doc.setForeground(new java.awt.Color(255, 255, 255));
        jPanel_Doc.setToolTipText("");

        jList_Persona.setBackground(new java.awt.Color(51, 51, 51));
        jList_Persona.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Account", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jList_Persona.setForeground(new java.awt.Color(255, 255, 255));
        jList_Persona.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList_PersonaValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jList_Persona);

        jList_Coms.setBackground(new java.awt.Color(51, 51, 51));
        jList_Coms.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Coms", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jList_Coms.setForeground(new java.awt.Color(255, 255, 255));
        jList_Coms.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList_ComsValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(jList_Coms);

        jList_Health.setBackground(new java.awt.Color(51, 51, 51));
        jList_Health.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Health", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jList_Health.setForeground(new java.awt.Color(255, 255, 255));
        jList_Health.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList_HealthValueChanged(evt);
            }
        });
        jScrollPane8.setViewportView(jList_Health);

        jList_Edu.setBackground(new java.awt.Color(51, 51, 51));
        jList_Edu.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Edu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jList_Edu.setForeground(new java.awt.Color(255, 255, 255));
        jList_Edu.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList_EduValueChanged(evt);
            }
        });
        jScrollPane9.setViewportView(jList_Edu);

        jList_Fam.setBackground(new java.awt.Color(51, 51, 51));
        jList_Fam.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Fam", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jList_Fam.setForeground(new java.awt.Color(255, 255, 255));
        jList_Fam.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList_FamValueChanged(evt);
            }
        });
        jScrollPane12.setViewportView(jList_Fam);

        jList_Dom.setBackground(new java.awt.Color(51, 51, 51));
        jList_Dom.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Dom", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jList_Dom.setForeground(new java.awt.Color(255, 255, 255));
        jList_Dom.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList_DomValueChanged(evt);
            }
        });
        jScrollPane6.setViewportView(jList_Dom);

        jList_FamDom.setBackground(new java.awt.Color(51, 51, 51));
        jList_FamDom.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Dom P", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jList_FamDom.setForeground(new java.awt.Color(255, 255, 255));
        jList_FamDom.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList_FamDomValueChanged(evt);
            }
        });
        jScrollPane11.setViewportView(jList_FamDom);

        javax.swing.GroupLayout jPanel_DocLayout = new javax.swing.GroupLayout(jPanel_Doc);
        jPanel_Doc.setLayout(jPanel_DocLayout);
        jPanel_DocLayout.setHorizontalGroup(
            jPanel_DocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_DocLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_DocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_DocLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_DocLayout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_DocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_DocLayout.setVerticalGroup(
            jPanel_DocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_DocLayout.createSequentialGroup()
                .addGroup(jPanel_DocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel_DocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_DocLayout.createSequentialGroup()
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane12))
                    .addComponent(jScrollPane6)
                    .addComponent(jScrollPane11))
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Educacion"));

        jTextArea_Edu.setBackground(new java.awt.Color(51, 51, 51));
        jTextArea_Edu.setColumns(20);
        jTextArea_Edu.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea_Edu.setRows(5);
        jTextArea_Edu.setBorder(javax.swing.BorderFactory.createTitledBorder("General"));
        jScrollPane1.setViewportView(jTextArea_Edu);

        jTextArea_Cert.setBackground(new java.awt.Color(51, 51, 51));
        jTextArea_Cert.setColumns(20);
        jTextArea_Cert.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea_Cert.setRows(5);
        jTextArea_Cert.setBorder(javax.swing.BorderFactory.createTitledBorder("Certificados"));
        jScrollPane4.setViewportView(jTextArea_Cert);

        jButton_GenEdu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/QR-Code-icon.png"))); // NOI18N
        jButton_GenEdu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GenEduActionPerformed(evt);
            }
        });

        jButton_Certi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/QR-Code-icon.png"))); // NOI18N
        jButton_Certi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CertiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_Certi)
                    .addComponent(jButton_GenEdu)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jButton_GenEdu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                    .addComponent(jButton_Certi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel8.setBackground(new java.awt.Color(51, 51, 51));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Personales"));

        jTextArea_Data.setBackground(new java.awt.Color(51, 51, 51));
        jTextArea_Data.setColumns(20);
        jTextArea_Data.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea_Data.setRows(5);
        jTextArea_Data.setBorder(javax.swing.BorderFactory.createTitledBorder("General"));
        jScrollPane7.setViewportView(jTextArea_Data);

        jButton_Datos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/QR-Code-icon.png"))); // NOI18N
        jButton_Datos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DatosActionPerformed(evt);
            }
        });

        jPanel7.setBackground(new java.awt.Color(51, 51, 51));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Domicilio"));

        jTextArea_Dom.setBackground(new java.awt.Color(51, 51, 51));
        jTextArea_Dom.setColumns(20);
        jTextArea_Dom.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea_Dom.setRows(5);
        jScrollPane5.setViewportView(jTextArea_Dom);

        jButton_Dom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/QR-Code-icon.png"))); // NOI18N
        jButton_Dom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Dom)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_Dom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        Coms.setBackground(new java.awt.Color(51, 51, 51));
        Coms.setColumns(20);
        Coms.setForeground(new java.awt.Color(255, 255, 255));
        Coms.setRows(5);
        Coms.setBorder(javax.swing.BorderFactory.createTitledBorder("Coms"));
        jScrollPane17.setViewportView(Coms);

        jButton_Com.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/QR-Code-icon.png"))); // NOI18N
        jButton_Com.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ComActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Datos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Com))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane7)
                    .addComponent(jButton_Datos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(jButton_Com, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(51, 51, 51));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Padres"));

        jPanel10.setBackground(new java.awt.Color(51, 51, 51));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Domicilio"));

        jTextArea_DomPad.setBackground(new java.awt.Color(51, 51, 51));
        jTextArea_DomPad.setColumns(20);
        jTextArea_DomPad.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea_DomPad.setRows(5);
        jScrollPane16.setViewportView(jTextArea_DomPad);

        jButton_PDom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/QR-Code-icon.png"))); // NOI18N
        jButton_PDom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_PDomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_PDom)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton_PDom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane16, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextArea_Padres.setBackground(new java.awt.Color(51, 51, 51));
        jTextArea_Padres.setColumns(20);
        jTextArea_Padres.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea_Padres.setRows(5);
        jScrollPane15.setViewportView(jTextArea_Padres);

        jButton_Padres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/QR-Code-icon.png"))); // NOI18N
        jButton_Padres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_PadresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Padres)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane15, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(jButton_Padres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Salud"));

        jTextArea_Vac.setBackground(new java.awt.Color(51, 51, 51));
        jTextArea_Vac.setColumns(20);
        jTextArea_Vac.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea_Vac.setRows(5);
        jTextArea_Vac.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Vacunas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jScrollPane13.setViewportView(jTextArea_Vac);

        jTextArea_Ale.setBackground(new java.awt.Color(51, 51, 51));
        jTextArea_Ale.setColumns(20);
        jTextArea_Ale.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea_Ale.setRows(5);
        jTextArea_Ale.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Alergias Y Padecimientos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jScrollPane14.setViewportView(jTextArea_Ale);

        jButton_HpGeneral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/QR-Code-icon.png"))); // NOI18N
        jButton_HpGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_HpGeneralActionPerformed(evt);
            }
        });

        jTextArea_GenHp.setBackground(new java.awt.Color(51, 51, 51));
        jTextArea_GenHp.setColumns(20);
        jTextArea_GenHp.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea_GenHp.setRows(5);
        jTextArea_GenHp.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "General", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jScrollPane10.setViewportView(jTextArea_GenHp);

        jButton_Vacunas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/QR-Code-icon.png"))); // NOI18N
        jButton_Vacunas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_VacunasActionPerformed(evt);
            }
        });

        jButton_Ale.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/QR-Code-icon.png"))); // NOI18N
        jButton_Ale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane13)
                            .addComponent(jScrollPane10)))
                    .addComponent(jScrollPane14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_HpGeneral)
                    .addComponent(jButton_Vacunas)
                    .addComponent(jButton_Ale)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane10)
                    .addComponent(jButton_HpGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane13, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                    .addComponent(jButton_Vacunas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane14, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(jButton_Ale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel_BackgroundLayout = new javax.swing.GroupLayout(jPanel_Background);
        jPanel_Background.setLayout(jPanel_BackgroundLayout);
        jPanel_BackgroundLayout.setHorizontalGroup(
            jPanel_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_BackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_Doc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel_BackgroundLayout.setVerticalGroup(
            jPanel_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BackgroundLayout.createSequentialGroup()
                .addComponent(jPanel_Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_Doc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel_BackgroundLayout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel_BackgroundLayout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BackActionPerformed
        // TODO add your handling code here:
        LogIn logIn = new LogIn();
        logIn.show();
        dispose();
    }//GEN-LAST:event_jButton_BackActionPerformed

    private void jButton_DatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DatosActionPerformed
        // TODO add your handling code here:
        try {
            ByteArrayOutputStream out = QRCode.from(jTextArea_Data.getText()).to(ImageType.PNG).stream();

            String Path_name = "D:\\";

            FileOutputStream fout = new FileOutputStream(new File(Path_name + ("DatosPersonales" + ".PNG")));
            fout.write(out.toByteArray());
            fout.flush();
            JOptionPane.showMessageDialog(this, "Qr Save in Drive D:");
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton_DatosActionPerformed

    private void jButton_ConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ConfigActionPerformed
        // TODO add your handling code here:
        User_Pass user_Pass = new User_Pass();
        user_Pass.setVisible(true);
        user_Pass.jLabel_User.setText(jLabel_User.getText());
        dispose();
    }//GEN-LAST:event_jButton_ConfigActionPerformed

    private void jList_PersonaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList_PersonaValueChanged
        // TODO add your handling code here:
        int index = this.jList_Persona.getSelectedIndex();
        Account account = (Account) this.ListModel1.getElementAt(index);
        //Account
        jLabel_Id.setText(account.getID());
        jTextArea_Data.setText("Name: " + account.getFirstName() + account.getSecondName() + " " + account.getLastName() + "\nDate of Birth:" + " " + account.getBDay() + "\tAge: " + account.getAge() + "\nNationality:" + " " + account.getNation() + "\nRFC #" + account.getIdIRS());
        jLabel_IdSS.setText(account.getSegSos());
        jLabel_IdEdu.setText(account.getIdEdu());
    }//GEN-LAST:event_jList_PersonaValueChanged

    private void jList_ComsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList_ComsValueChanged
        // TODO add your handling code here:
        int index = this.jList_Coms.getSelectedIndex();
        Account_Coms account_Coms = (Account_Coms) this.ListModel2.getElementAt(index);
        Coms.setText("Tel: " + account_Coms.getTel() + "\nEmail: " + account_Coms.getEmail());
    }//GEN-LAST:event_jList_ComsValueChanged

    private void jList_HealthValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList_HealthValueChanged
        // TODO add your handling code here:
        int index = this.jList_Health.getSelectedIndex();
        Account_Health account_Healt = (Account_Health) this.ListModel4.getElementAt(index);
        jTextArea_GenHp.setText("Tipo de sangre: " + account_Healt.getBloodType() + "\nAltura: " + account_Healt.getCm() + "\tPeso: " + account_Healt.getKg() + "\tSexo: " + account_Healt.getSex());
        jTextArea_Ale.setText(account_Healt.getPedecimiento());
        jTextArea_Vac.setText(account_Healt.getVaccine());
    }//GEN-LAST:event_jList_HealthValueChanged

    private void jList_EduValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList_EduValueChanged
        // TODO add your handling code here:
        int index = this.jList_Edu.getSelectedIndex();
        Account_Studies account_Studies = (Account_Studies) this.ListModel6.getElementAt(index);
        jTextArea_Edu.setText("Estudiando: " + account_Studies.getStudying() + "\nGrados de estudio:" + account_Studies.getDegree());
        jTextArea_Cert.setText(account_Studies.getCertification());
    }//GEN-LAST:event_jList_EduValueChanged

    private void jList_FamValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList_FamValueChanged
        // TODO add your handling code here:
        int index = this.jList_Fam.getSelectedIndex();
        Family_Data family_Data = (Family_Data) this.ListModel7.getElementAt(index);
        jTextArea_Padres.setText("Padre: " + family_Data.getNameFather() + "\nMadre: " + family_Data.getNameMother() + "\nOcupacion " + family_Data.getOcupations() + "\tEstatus " + family_Data.getStatus());
    }//GEN-LAST:event_jList_FamValueChanged

    private void jList_DomValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList_DomValueChanged
        // TODO add your handling code here:
        int index = this.jList_Dom.getSelectedIndex();
        Account_Dom account_Dom = (Account_Dom) this.ListModel3.getElementAt(index);
        jTextArea_Dom.setText("Num Ext #" + account_Dom.getNumExt() + "\tNum Int #" + account_Dom.getNumInt() + "\nEdificio #" + account_Dom.getBuilding() + "\tCodigo Postal #" + account_Dom.getZp() + "\nCalle: " + account_Dom.getStreet() + "\nReferencias " + account_Dom.getRef());
    }//GEN-LAST:event_jList_DomValueChanged

    private void jList_FamDomValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList_FamDomValueChanged
        // TODO add your handling code here:
        int index = this.jList_FamDom.getSelectedIndex();
        Family_Dom family_Dom = (Family_Dom) this.ListModel5.getElementAt(index);
        jTextArea_DomPad.setText("Num Ext #" + family_Dom.getNumExtFam() + "\tNum Int #" + family_Dom.getNumIntFam() + "\nEdificio #" + family_Dom.getBuildingFam() + "\tCodigo Postal #" + family_Dom.getZpFam() + "\nCalle: " + family_Dom.getStreetFam() + "\nReferencias " + family_Dom.getRef());
    }//GEN-LAST:event_jList_FamDomValueChanged

    private void jButton_RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RefreshActionPerformed
        // TODO add your handling code here:
        String[] ComData = new String[3];
        String[] EduData = new String[4];
        String[] HealthData = new String[7];
        String[] ParentsData = new String[6];
        String[] DomData = new String[7];
        String[] FamDomData = new String[7];
        try {
            Connection connection = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/dbqr", "root", "");
            PreparedStatement AccountCom = connection.prepareStatement("SELECT * FROM account_coms WHERE account_coms.Account_idData_User=?");
            AccountCom.setString(1, jLabel_Id.getText());
            ResultSet RS2 = AccountCom.executeQuery();
            while (RS2.next()) {
                ComData[0] = RS2.getString(1);
                ComData[1] = RS2.getString(2);
                ComData[2] = RS2.getString(3);
                Account_Coms account_Coms = new Account_Coms(ComData[0], ComData[1], ComData[2]);
                this.ListModel2.addElement(account_Coms);
            }
            PreparedStatement AccountEdu = connection.prepareStatement("SELECT * FROM account_education WHERE account_education.Matricula=?");
            AccountEdu.setString(1, jLabel_IdEdu.getText());
            ResultSet RS3 = AccountEdu.executeQuery();
            while (RS3.next()) {
                EduData[0] = RS3.getString(1);
                EduData[1] = RS3.getString(2);
                EduData[2] = RS3.getString(3);
                EduData[3] = RS3.getString(4);
                Account_Studies account_Studies = new Account_Studies(EduData[0], EduData[1], EduData[2], EduData[3]);
                this.ListModel6.addElement(account_Studies);
            }
            PreparedStatement AccountHealth = connection.prepareStatement("SELECT * FROM account_health WHERE account_health.num_seguro_social=?");
            AccountHealth.setString(1, jLabel_IdSS.getText());
            ResultSet RS4 = AccountHealth.executeQuery();
            while (RS4.next()) {
                HealthData[0] = RS4.getString(1);
                HealthData[1] = RS4.getString(2);
                HealthData[2] = RS4.getString(3);
                HealthData[3] = RS4.getString(4);
                HealthData[4] = RS4.getString(5);
                HealthData[5] = RS4.getString(6);
                HealthData[6] = RS4.getString(7);
                Account_Health account_Healt = new Account_Health(HealthData[0], HealthData[1], HealthData[2], HealthData[3], HealthData[4], HealthData[5], HealthData[6]);
                this.ListModel4.addElement(account_Healt);
            }
            PreparedStatement AccountParents = connection.prepareStatement("SELECT* FROM parents WHERE parents.Account_idData_User=?");
            AccountParents.setString(1, jLabel_Id.getText());
            ResultSet RS5 = AccountParents.executeQuery();
            while (RS5.next()) {
                ParentsData[0] = RS5.getString(1);
                ParentsData[1] = RS5.getString(2);
                ParentsData[2] = RS5.getString(3);
                ParentsData[3] = RS5.getString(4);
                ParentsData[4] = RS5.getString(5);
                Family_Data family_Data = new Family_Data(ParentsData[0], ParentsData[1], ParentsData[2], ParentsData[3], ParentsData[4]);
                this.ListModel7.addElement(family_Data);
            }
            PreparedStatement AccountDom = connection.prepareStatement("SELECT * FROM account_dom WHERE account_dom.IdPersonal_Dom=?");
            AccountDom.setString(1, jLabel_Id.getText());
            ResultSet RS6 = AccountDom.executeQuery();
            while (RS6.next()) {
                DomData[0] = RS6.getString(1);
                DomData[1] = RS6.getString(2);
                DomData[2] = RS6.getString(3);
                DomData[3] = RS6.getString(4);
                DomData[4] = RS6.getString(5);
                DomData[5] = RS6.getString(6);
                DomData[6] = RS6.getString(7);
                Account_Dom account_Dom = new Account_Dom(DomData[0], DomData[1], DomData[2], DomData[3], DomData[4], DomData[5], DomData[6]);
                this.ListModel3.addElement(account_Dom);
            }
            PreparedStatement ParentsDom = connection.prepareStatement("SELECT * FROM parents_dom WHERE parents_dom.IdFamilyDom=?");
            ParentsDom.setString(1, jLabel_Id.getText());
            ResultSet RS7 = ParentsDom.executeQuery();
            while (RS7.next()) {
                FamDomData[0] = RS7.getString(1);
                FamDomData[1] = RS7.getString(2);
                FamDomData[2] = RS7.getString(3);
                FamDomData[3] = RS7.getString(4);
                FamDomData[4] = RS7.getString(5);
                FamDomData[5] = RS7.getString(6);
                FamDomData[6] = RS7.getString(7);
                Family_Dom family_Dom = new Family_Dom(FamDomData[0], FamDomData[1], FamDomData[2], FamDomData[3], FamDomData[4], FamDomData[5], FamDomData[6]);
                this.ListModel5.addElement(family_Dom);
            }
            connection.close();
        } catch (SQLException e) {
            System.out.println("Error while connecting to the database");
        }
    }//GEN-LAST:event_jButton_RefreshActionPerformed

    private void jButton_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SearchActionPerformed
        // TODO add your handling code here:
        String[] PData = new String[13];
        try {
            Connection connection = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/dbqr", "root", "");
            PreparedStatement Account = connection.prepareStatement("SELECT * FROM account WHERE account.Curp=?");
            Account.setString(1, jLabel_User.getText());
            ResultSet RS = Account.executeQuery();
            while (RS.next()) {
                PData[0] = RS.getString(1);
                PData[1] = RS.getString(2);
                PData[2] = RS.getString(3);
                PData[3] = RS.getString(4);
                PData[4] = RS.getString(5);
                PData[5] = RS.getString(6);
                PData[6] = RS.getString(7);
                PData[7] = RS.getString(8);
                PData[8] = RS.getString(9);
                PData[9] = RS.getString(10);
                PData[10] = RS.getString(11);
                PData[11] = RS.getString(12);
                PData[12] = RS.getString(13);
                Account account = new Account(PData[0], PData[1], PData[2], PData[3], PData[4],
                        PData[5], PData[6], PData[7], PData[8], PData[9], PData[10], PData[11], PData[12]);
                this.ListModel1.addElement(account);
            }
        } catch (SQLException e) {
            System.out.println("Error while connecting to the database");
        }
    }//GEN-LAST:event_jButton_SearchActionPerformed

    private void jButton_DomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DomActionPerformed
        // TODO add your handling code here:
        try {
            ByteArrayOutputStream out = QRCode.from(jTextArea_Data.getText()).to(ImageType.PNG).stream();

            String Path_name = "D:\\";

            FileOutputStream fout = new FileOutputStream(new File(Path_name + ("Dom" + ".PNG")));
            fout.write(out.toByteArray());
            fout.flush();
            JOptionPane.showMessageDialog(this, "Qr Save in Drive D:");
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton_DomActionPerformed

    private void jButton_PDomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_PDomActionPerformed
        // TODO add your handling code here:
        try {
            ByteArrayOutputStream out = QRCode.from(jTextArea_Data.getText()).to(ImageType.PNG).stream();

            String Path_name = "D:\\";

            FileOutputStream fout = new FileOutputStream(new File(Path_name + ("Padres Domicilio" + ".PNG")));
            fout.write(out.toByteArray());
            fout.flush();
            JOptionPane.showMessageDialog(this, "Qr Save in Drive D:");
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton_PDomActionPerformed

    private void jButton_PadresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_PadresActionPerformed
        // TODO add your handling code here:
        try {
            ByteArrayOutputStream out = QRCode.from(jTextArea_Data.getText()).to(ImageType.PNG).stream();

            String Path_name = "D:\\";

            FileOutputStream fout = new FileOutputStream(new File(Path_name + ("Padres" + ".PNG")));
            fout.write(out.toByteArray());
            fout.flush();
            JOptionPane.showMessageDialog(this, "Qr Save in Drive D:");
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton_PadresActionPerformed

    private void jButton_HpGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_HpGeneralActionPerformed
        // TODO add your handling code here:
        try {
            ByteArrayOutputStream out = QRCode.from(jTextArea_Data.getText()).to(ImageType.PNG).stream();

            String Path_name = "D:\\";

            FileOutputStream fout = new FileOutputStream(new File(Path_name + ("GeneralSalud" + ".PNG")));
            fout.write(out.toByteArray());
            fout.flush();
            JOptionPane.showMessageDialog(this, "Qr Save in Drive D:");
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton_HpGeneralActionPerformed

    private void jButton_VacunasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VacunasActionPerformed
        // TODO add your handling code here:
        try {
            ByteArrayOutputStream out = QRCode.from(jTextArea_Data.getText()).to(ImageType.PNG).stream();

            String Path_name = "D:\\";

            FileOutputStream fout = new FileOutputStream(new File(Path_name + ("Vacunas" + ".PNG")));
            fout.write(out.toByteArray());
            fout.flush();
            JOptionPane.showMessageDialog(this, "Qr Save in Drive D:");
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton_VacunasActionPerformed

    private void jButton_AleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AleActionPerformed
        // TODO add your handling code here:
        try {
            ByteArrayOutputStream out = QRCode.from(jTextArea_Data.getText()).to(ImageType.PNG).stream();

            String Path_name = "D:\\";

            FileOutputStream fout = new FileOutputStream(new File(Path_name + ("Alergias & Padecimientos" + ".PNG")));
            fout.write(out.toByteArray());
            fout.flush();
            JOptionPane.showMessageDialog(this, "Qr Save in Drive D:");
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton_AleActionPerformed

    private void jButton_GenEduActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GenEduActionPerformed
        // TODO add your handling code here:
        try {
            ByteArrayOutputStream out = QRCode.from(jTextArea_Data.getText()).to(ImageType.PNG).stream();

            String Path_name = "D:\\";

            FileOutputStream fout = new FileOutputStream(new File(Path_name + ("Educacion General" + ".PNG")));
            fout.write(out.toByteArray());
            fout.flush();
            JOptionPane.showMessageDialog(this, "Qr Save in Drive D:");
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton_GenEduActionPerformed

    private void jButton_CertiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CertiActionPerformed
        // TODO add your handling code here:
        try {
            ByteArrayOutputStream out = QRCode.from(jTextArea_Data.getText()).to(ImageType.PNG).stream();

            String Path_name = "D:\\";

            FileOutputStream fout = new FileOutputStream(new File(Path_name + ("Certificaciones" + ".PNG")));
            fout.write(out.toByteArray());
            fout.flush();
            JOptionPane.showMessageDialog(this, "Qr Save in Drive D:");
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton_CertiActionPerformed

    private void jButton_ComActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ComActionPerformed
        // TODO add your handling code here:
        try {
            ByteArrayOutputStream out = QRCode.from(jTextArea_Data.getText()).to(ImageType.PNG).stream();

            String Path_name = "D:\\";

            FileOutputStream fout = new FileOutputStream(new File(Path_name + ("Coms" + ".PNG")));
            fout.write(out.toByteArray());
            fout.flush();
            JOptionPane.showMessageDialog(this, "Qr Save in Drive D:");
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton_ComActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User_QR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User_QR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User_QR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User_QR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User_QR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Coms;
    private javax.swing.JButton jButton_Ale;
    private javax.swing.JButton jButton_Back;
    private javax.swing.JButton jButton_Certi;
    private javax.swing.JButton jButton_Com;
    private javax.swing.JButton jButton_Config;
    private javax.swing.JButton jButton_Datos;
    private javax.swing.JButton jButton_Dom;
    private javax.swing.JButton jButton_GenEdu;
    private javax.swing.JButton jButton_HpGeneral;
    private javax.swing.JButton jButton_PDom;
    private javax.swing.JButton jButton_Padres;
    private javax.swing.JButton jButton_Refresh;
    private javax.swing.JButton jButton_Search;
    private javax.swing.JButton jButton_Vacunas;
    public static javax.swing.JLabel jLabel_Id;
    public static javax.swing.JLabel jLabel_IdEdu;
    public static javax.swing.JLabel jLabel_IdSS;
    public static javax.swing.JLabel jLabel_User;
    private javax.swing.JList<String> jList_Coms;
    private javax.swing.JList<String> jList_Dom;
    private javax.swing.JList<String> jList_Edu;
    private javax.swing.JList<String> jList_Fam;
    private javax.swing.JList<String> jList_FamDom;
    private javax.swing.JList<String> jList_Health;
    private javax.swing.JList<String> jList_Persona;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanel_Background;
    private javax.swing.JPanel jPanel_Doc;
    private javax.swing.JPanel jPanel_Header;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea jTextArea_Ale;
    private javax.swing.JTextArea jTextArea_Cert;
    private javax.swing.JTextArea jTextArea_Data;
    private javax.swing.JTextArea jTextArea_Dom;
    private javax.swing.JTextArea jTextArea_DomPad;
    private javax.swing.JTextArea jTextArea_Edu;
    private javax.swing.JTextArea jTextArea_GenHp;
    private javax.swing.JTextArea jTextArea_Padres;
    private javax.swing.JTextArea jTextArea_Vac;
    // End of variables declaration//GEN-END:variables
}
